### ISSUE TITLE
support `scripts.postinstall` like syntax for `fields`, or provide a way to override exceptions

### ISSUE THREAD

**Issue by JounQin** [shashkovdanil/clean-publish#101]
My `package.json` contains `{"postinstall": "simple-git-hooks && yarn-deduplicate --strategy fewer || exit 0"}`, it is unexpected to preserve on publishing.

I just found I could change it to `prepare`, but it would be better to override this package's config.

**Comment by ai** [comment]
Removing this field will be unexpected for most of users (contributors to your project). I recommend you to moving to `prepare` in this case.

**Comment by JounQin** [comment]
Or could it be documented better.
