### ISSUE TITLE
Error: Cannot find module 'package.json'

### ISSUE THREAD

**Issue by JounQin** [shashkovdanil/clean-publish#110]
![image](https://user-images.githubusercontent.com/8336744/118075438-93e26280-b3e2-11eb-88f8-28502aae5a04.png)

It runs failed on GitLab runner.

![image](https://user-images.githubusercontent.com/8336744/118075501-a9578c80-b3e2-11eb-8947-4678676d78c8.png)

**Comment by JounQin** [comment]
![image](https://user-images.githubusercontent.com/8336744/118075551-ce4bff80-b3e2-11eb-8e8d-ceee62758cb8.png)

I can reproduce it on Node REPL.

**Comment by ai** [comment]
What do you call to get this error?

Do you have a reproduction repo?

**Comment by JounQin** [comment]
> What do you call to get this error?

`npx clean-publish --tag latest`

> Do you have a reproduction repo?

Not yet, it's a private repo.

It should be related to [`lilconfig`](https://github.com/antonk52/lilconfig/issues/17) maybe.

**Comment by ai** [comment]
Where is your `package.json` and where do you call `clean-publish` (is it inside subfolder?)

**Comment by ai** [comment]
I am closing this issue. Please post more details to `lilconfig` issue.

**Comment by JounQin** [comment]
@ai Any chance to use `cosmiconfig` instead? I believe the size is not a key point of this package.

**Comment by ai** [comment]
@JounQin `node_modules` size is a big problem of the community. But also having too many dependencies increase security risks.

Why this issue can’t be solved in `lilconfig`? How `lilconfig` reacted on the issue?

**Comment by JounQin** [comment]
There is no response from `lilconfig` yet, and no active commit since 4 Dec 2020.

**Comment by ai** [comment]
@JounQin I recently talked with `lilconfig` author on Twitter. He is still active.

If you do not have opened issues, you do not need to commit new changes to the repo.

**Comment by JounQin** [comment]
Well, that issue https://github.com/antonk52/lilconfig/issues/17 has been opened 12 days. 😂

That is a bit difficult to debug because it only occurred on GitLab CI runner, I'm not sure how to help to fix in `lilconfig`.
