### ISSUE TITLE
Scripts aren't ignore, which causes an endless loop

### ISSUE THREAD

**Issue by NickKaramoff** [shashkovdanil/clean-publish#134]
I want to use `clean-publish`, so I add the `publish` script to my `package.json`:

```json
"scripts": {
    "publish": "clean-publish",
    "postversion": "some postversion script",
    "test": "some test script"
}
```

If I now run `clean-publish --dry-run` (to see what gets exported), but the process gets caught in an endless loop.

I tried to investigate; when I look into the cleaned `package.json`, I notice the following:

```json
"scripts": {
    "publish": "clean-publish",
    "postversion": "some postversion script"
}
```

The `publish` script isn't deleted and is thus being called over and over. Inside the temporary directory, I notice an endless tree of temporary directories.

**Comment by ai** [comment]
You should use `clean-publish` by replacing `npm publish` command with `npx clean-publish`.

Adding it to `publish` is not the right way.

**Comment by NickKaramoff** [comment]
Oh, okay; this is nowhere in the [usage docs](https://github.com/shashkovdanil/clean-publish#usage) 🤷‍♂️

**Comment by ai** [comment]
Hm. Can you send PR which will clean `package.publish` only if it is equal to `clean-publish`?

**Comment by NickKaramoff** [comment]
> Hm. Can you send PR which will clean `package.publish` only if it is equal to `clean-publish`?

I can attempt to later today 👌
