### ISSUE TITLE
Why not the files field in package.json?

### ISSUE THREAD

**Issue by avdeev** [shashkovdanil/clean-publish#14]
It allows you to specify a white list of files to publish

https://docs.npmjs.com/files/package.json#files

**Comment by shashkovdanil** [comment]
While I see two usages for the whitelist:

1. Display a warning if the user entered the required file in the `files` argument
2. Show a warning if there is no file from the whitelist.

Any other ideas?

Rus:

Пока вижу два юзкейса для белого списка:

1. Показать предупреждение, если пользователь ввёл обязательный файл в аргумент `files`
2. Показать предупреждение, если файла из белого списка нет.

Ещё идеи? 

cc @avdeev

**Comment by avdeev** [comment]
@shashkovdanil Я не совсем это имел ввиду.

Я не очень понял смысл этой утилиты.
Ведь есть же то самое поле `files`, которое является белым списком для файлов при публикации пакета в NPM.
Почему его недостаточно и нужна еще чистка перед публикацией?
Или это больше не чистка перед публикацией, а валидатор правильной публикации? :)

Возможно, стоит добавить пару предложений об этом в Readme?

**Comment by avdeev** [comment]
@shashkovdanil Понял. Сделать PR с дополнением Readme?

**Comment by shashkovdanil** [comment]
@avdeev, да. Спасибо!

**Comment by retyui** [comment]
добавил конфиг 

но в итоге в пакете прилетают файлы тестов
```js
'use strict';

const glob = require('glob');

module.exports = {
  files: [
    ...glob.sync('src/**/*.test.js'),
    //...
  ],
  packageManager: 'yarn',
};

```
