### ISSUE TITLE
Global user npm

### ISSUE THREAD

**Issue by shashkovdanil** [shashkovdanil/clean-publish#15]
@ai, не получается установить npm пользователя глобально. После перехода в tmp директорию и попытки выполнить `npm publish` просит выполнить `npm adduser`.

**Comment by ai** [comment]
Учти что сегодня *всем пользователям* сбросили доступ в npm (из-за взлома). Надо занового залогинется.

**Comment by shashkovdanil** [comment]
@ai, убрал `process.chdir()`, теперь рабочая директория устанавливается как опция `cwd` spawn.

Утилита корректно работает, последнюю версию в npm опубликовал, используя её.
