### ISSUE TITLE
Current state

### ISSUE THREAD

**Issue by shashkovdanil** [shashkovdanil/clean-publish#17]
Реализовано:
- Копирование только нужных файлов в tmp директорию
- Удаление ненужных полей и скриптов из package.json
- Установка доп. файлов и полей через аргументы
- Выполнение `npm publish` после копирования файлов и очистки package.json
- Удаление tmp директории после публикации

Осталось сделать:
- Написать тесты
- Убрать ненужные скрипты из файла `npm-scripts.js`
- Подумать над новыми фичами и составить их список

@ai, можешь пожалуйста провести код-ревью и посмотреть библиотеку?

**Comment by ai** [comment]
Сделай чистку ненужных скриптов и первый этап будет готов.

**Comment by shashkovdanil** [comment]
@ai, убрал ненужные скрипты https://github.com/shashkovdanil/clean-publish/commit/932108c727f576c1593deba1c7d1a59f72c644e7

**Comment by ai** [comment]
Отлично. Сегодня вечером изучу.
