### ISSUE TITLE
Use separated commit for releases

### ISSUE THREAD

**Issue by ai** [shashkovdanil/clean-publish#20]
Right now I can't see what commits was released. This is why we have this best practices:

1. Use separated `Release x.x.x` commit to update `version` in `package.json` and add section to ChangeLog.
2. Sign this commit by `git tag -s x.x.x` (`x.x.x` is a version number). You may need to have PGP keys. Upload them to GitHub, so GitHub will show that this release was made by you and not by a hacker.

**Comment by shashkovdanil** [comment]
Complete: https://github.com/shashkovdanil/clean-publish/releases
