### ISSUE TITLE
Use real temporary dir

### ISSUE THREAD

**Issue by ai** [shashkovdanil/clean-publish#3]
`./tmp` dir in the current dir is a bad idea since:

1. The project maybe have it for a different purpose
2. If you tool will throw a error `tmp/` dir will not be cleaned

Node.js has a special API to create tmp dirs

**Comment by Kelin2025** [comment]
What do we need from temporary dir? Just move ignored files until it's published or,.?

**Comment by shashkovdanil** [comment]
Completed: https://github.com/shashkovdanil/clean-publish/blob/master/clean-publish.js#L15
