### ISSUE TITLE
Feature: Auto-run prepublish script

### ISSUE THREAD

**Issue by retyui** [shashkovdanil/clean-publish#32]
I think this tool has to run `prepublishOnly` or `prepublish` scripts from `package.json` after start clone some files

**Comment by retyui** [comment]
@shashkovdanil 

https://github.com/shashkovdanil/clean-publish/blob/5bd50640cd64a9c8f0503bfce25133fafc6a1826/exception/npm-scripts.js#L6

> prepublishOnly: Run BEFORE the package is prepared and packed, ONLY on npm publish. (See below.)

https://docs.npmjs.com/misc/scripts

**Comment by ai** [comment]
`prepublish` can change only the current dir, which is not a case to remove development files
