### ISSUE TITLE
Allow to run script on the to-release dir

### ISSUE THREAD

**Issue by ai** [shashkovdanil/clean-publish#39]
I want to run a small script during the release (which will transform ESM files to CJS). `clean-publish` is a perfect place.

I am suggesting this API. `package.json`:

```json
  "clean-publish": {
    "beforeScript": "esm-compiler"
  }
```

`clean-publish` will call `esm-compiler /home/ai/Dev/project/tmp-jv4j3hvj3`.

@shashkovdanil what do you think?

**Comment by ai** [comment]
@shashkovdanil do you need PR for it?

**Comment by shashkovdanil** [comment]
@ai, yes, ty
