### ISSUE TITLE
Suggestion: use regexps

### ISSUE THREAD

**Issue by Kelin2025** [shashkovdanil/clean-publish#8]
Hi, nice idea!

But it might be useful to use regexps in ignore list too. Because even ESLint has 5 variations of config name:

![image](https://user-images.githubusercontent.com/4208480/42563387-c9db808c-8506-11e8-9118-8397a4b9cf57.png)

Better use one regexp rather than copy-paste each variation I think 🤔

**Comment by Kelin2025** [comment]
It will drop Node 6

**Comment by shashkovdanil** [comment]
Completed: https://github.com/shashkovdanil/clean-publish/blob/master/clean-publish.js#L19
